Dockerfile
This is a breaking change for those who use the docker image, but oh well.
=> Fix config.yml reference in dockerfile

src/FormatUtil.ts
Use ⤵instead of :hand:.
Looks better in a client with proper emoji support:
=> Use an arrow instead of hand to signify a PR

config.sample.yml, src/Config/Config.ts, src/Config/Defaults.ts, src/Connections/GenericHook.ts, src/Connections/GithubIssue.ts, src/Connections/GithubRepo.ts, src/Connections/GithubUserSpace.ts, src/Connections/GitlabRepo.ts, src/GithubBridge.ts, src/Webhooks.ts, tests/AdminRoomTest.ts, tests/FormatUtilTest.ts
This PR allows the bridge to handle any events sent to it, without knowing the format. Users can describe the transformation function of the data in state for the resulting message, which is executed in a secure JS context.
=> Add support for handling generic webhooks

src/ConnectionManager.ts, src/Connections/GenericHook.ts
To avoid hookId piracy where one room could potentially subscribe to info intended for another room.
=> Ensure webhook hookIds are stored internally

src/AdminRoom.ts, src/BotCommands.ts, src/Bridge.ts, src/Connections/CommandConnection.ts, src/Connections/GithubRepo.ts, src/Connections/IConnection.ts, src/FormatUtil.ts, src/Github/Router.ts
- Issues created with `!gh create` show the issue number inside a reaction.
- Small PRs now show the diff inline, optionally.
- Users can review PRs by relying with a :heavy_check_mark: or a :x: and some review text.
=> Various usability tweaks to GitHubRepo connections

.github/workflows/main.yml, changelog.d/97.misc
We have CI to check if the sample config has changed, but it doesn't show you the diff.
=> Make sample config CI diff visible

changelog.d/143.feature, src/AdminRoom.ts, src/BotCommands.ts, src/Github/AdminCommands.ts, src/Jira/AdminCommands.ts, tests/AdminRoomTest.ts
Fixes #138
Bot commands are now categorized according to service, and the help text is now generated based on the configuration. Commands should already be checking for whether a service is active before executing, so this should solve the case where commands are given in help but are not enabled.
=> Support categorising bot commands

changelog.d/144.feature, src/Connections/GithubRepo.ts
Fixes #139 
This is useful where a issue has been closed / reopened and some explanatory text has been added. To avoid spam, this only looks for messages sent in the last 2 minutes.
=> Mention the last comment on a recently closed/reopened issue.

changelog.d/176.feature, docs/usage/room_configuration/github_repo.md, src/Bridge.ts, src/Connections/GithubRepo.ts
So that rooms can subscribe to issues *after* an issue has been labeled.
=> Send a notice to a room when a GitHub issue has been labeled matching a includesLabel

Dockerfile, changelog.d/184.misc
It doesn't seem to be necessary to install Rust.
Passing `--target` prevents the Dockerfile from being built on different architectures.
Not passing it makes it auto-detect what to install.
Actually, I've managed to build this Dockerfile on ARM64 even with the hardcoded `--target`. It's misleading though, so removing it is better.
Discussed here: https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/1505
=> Do not explicitly pass --target to rustup

.github/workflows/main.yml, Cargo.toml, changelog.d/228.removal, docs/setup.md, package.json, src/UserTokenStore.ts, tsconfig.json, yarn.lock
Node 12 becomes EOL in April https://nodejs.org/en/about/releases/
=> Drop support for Node 12

changelog.d/229.feature, config.sample.yml, docs/setup.md, src/App/BridgeApp.ts, src/App/GithubWebhookApp.ts, src/App/MatrixSenderApp.ts, src/Bridge.ts, src/Config/Config.ts, src/Config/Defaults.ts, src/ConnectionManager.ts, src/Connections/FigmaFileConnection.ts, src/ListenerService.ts, src/LogWrapper.ts
Fixes #195 
This PR refactors the logs to be much less noisy on startup, and also include some new features such as `json` outputting and colorizing. The logging configuration is now documented in docs/.
=> Refactor logging to be much more flexible and less noisy

changelog.d/227.feature, config.sample.yml, docs/setup/webhooks.md, src/Bridge.ts, src/Config/Config.ts, src/Config/Defaults.ts, src/Connections/GenericHook.ts, src/Connections/SetupConnection.ts, src/Webhooks.ts, src/generic/Router.ts, src/generic/types.ts, src/provisioning/api.ts
The generic webhooks router currently listens on `/:hookId/` which means that while the request paths are short, it causes confusion when a user misconfigures their bridge and gets a 200 response regardless. This PR makes the bridge *prefer* `/webhook`, while still supporting `/:hookId`. 
In addition, the bridge now gives an appropriate 404 from both paths when a hookId is not found. The bridge *can* also be configured to wait until the webhook has finished processing before responding, although this behavior is off by default.
=> Move webhooks from / to /webhook

changelog.d/250.misc, src/Config/Config.ts
Even though they aren't strictly valid, it seems to be a common mistake that people will use `DEBUG` instead of `debug`. To make life easier, let's put it through `toLowerCase`. For extra points, the Config now validates the log level.
=> Allow uppercase log levels

changelog.d/257.bugfix, src/Bridge.ts, src/ConnectionManager.ts, src/provisioning/provisioner.ts
Fixes #255 
This doesn't purge the state events (that needs to be done with a more forceful action like a command), but crucially when the bot parts the room, all the connections in that room stop working so the bot doesn't try to rejoin and carry on.
=> Remove connections from a room when the bot leaves

.github/workflows/docs-latest.yml, .github/workflows/docs-release.yml, book.toml, changelog.d/258.feature, docs/_site/main.js, docs/_site/version.js
Fixes #231 
This PR changes our CI to compile seperate `/latest` and `/X.Y.Z` documentation sets. This also adds a version selector to the documentation page.
=> Support versioning docs

changelog.d/265.feature, src/Bridge.ts, src/Connections/SetupConnection.ts
Fixes https://github.com/matrix-org/matrix-hookshot/issues/161
This simply posts the webhook url to the admin room of the user (creating one if necessary)
=> Send webhook URLs to the admin room

changelog.d/272.bugfix, web/BridgeAPI.ts
Only set "Content-Type" if we are sending a JSON body.
`undefined` (or empty string) aren't valid JSON, so it might make naïve web servers fail.
=> Only set Content-Type if we send a body

changelog.d/282.feature, docs/setup/webhooks.md, src/Connections/GenericHook.ts
So we can send noisy m.text notifications.
Addresses the jstransform part of https://github.com/matrix-org/matrix-hookshot/issues/179.
Signed-off-by: Tobias Büttner <dev@spiritcroc.de>
=> Generic webhook transform: allow specifying msgtype

changelog.d/298.misc, config.sample.yml, docs/advanced/widgets.md, src/Config/Config.ts, src/Config/Defaults.ts, src/errors.ts
Fixes https://github.com/matrix-org/matrix-hookshot/issues/288
This also:
- Causes the config validator to fail
- Improves the documentation by adding a note about listeners
- Converts existing config errors into `ConfigError` which helps with formatting.
=> Fail to start when widgets are configured without a listener

changelog.d/303.bugfix, config.sample.yml, src/Bridge.ts, src/Config/Config.ts, src/Config/Defaults.ts, src/ConnectionManager.ts, src/Connections/GithubDiscussion.ts, src/Connections/GithubIssue.ts, src/Connections/GitlabIssue.ts, src/IntentUtils.ts
This has been broken for a while, as we were relying on the bot-sdk's native support for userId generation. However, this is broken because we use have several userId prefixes in use. As a bonus, both GitHub and GitLab prefix's are now configurable.
=> Fix GitHub and GitLab ghost user intent creation

changelog.d/307.bugfix, src/Github/AdminCommands.ts, src/Github/GithubInstance.ts, src/UserTokenStore.ts, src/errors.ts
Whenever a token expires, we try to refresh it. Sadly, we didn't check the response format of the refresh request which was turning up as a querystring. This meant that we were inadvertently saving tokens as empty objects, and therefore everyone's token would eventually break.
This also changes the `github hastoken` command into `github status`, which is better as it doesn't presume the type of token you are using.
=> Fix GitHub refresh tokens not refreshing

changelog.d/314.feature, src/Bridge.ts, src/Connections/GithubRepo.ts, src/Connections/GitlabRepo.ts, src/Gitlab/WebhookTypes.ts
This one was a bit tricky. GitLab doesn't have a notion of "review comments" so we've had to play a bit of a game to make it work like we have on GitHub.
Specifically, we determine a GitLab review by the following:
- Did a note come in for a Merge Request
- Was the note *not* from the original MR author
We also batch together several notes for the same MR into one matrix message if several of them arrive in a short period of time (5s), since GitLab sends the review comments at the same time.
I'm not particularly happy with this approach, but I think it's probably better than not having them.
=> Support notifying on gitlab review comments

Dockerfile, changelog.d/319.misc
I noticed our images were exceeding 500MBs...which felt wrong. Turns out you can help a lot by clearing the cache after installing.
=> Clean cache, and don't generate a lockfile

Dockerfile, changelog.d/336.misc
This saves us quuuuite a lot of space on the image. To the tune of 1.37GB -> 300MB
=> Use node:16-slim for final image build

changelog.d/340.bugfix, vite.config.js
Because setting the path as an absolute will break people running things on not-the-default-path
=> Relative path for assets

changelog.d/326.feature, config.sample.yml, docs/advanced/widgets.md, src/Config/Config.ts, src/Config/Defaults.ts, src/Widgets/BridgeWidgetApi.ts
This is a config option I'd only expect to be used in dev environments, but it basically allows you to map a server hostname to a federation S-S API path for local dev so you don't need a working federated environment to test changes. It's a bit niche, but I've found it useful.
=> Allow overriding the results of an openID lookup for widgets for local development.

changelog.d/362.bugfix, src/Connections/GitlabRepo.ts
Fixes #361 
We don't need to check for `github` when setting up GitLab.
=> Fix issue where GitLab support would break if GitHub wasn't also configured

README.md, changelog.d/389.doc
While looking into adding an RSS feed into a room I first looked at hookshot's readme and thought it didn't support it because it made no mention of it.
=> Mention RSS/Atom feeds in the list of supported platforms

.github/workflows/docker-hub-latest.yml, .github/workflows/docker-hub-release.yml, changelog.d/373.feature
Reverts matrix-org/matrix-hookshot#373
Fixes #390. Sadly https://github.com/matrix-org/matrix-rust-sdk-bindings does not compile successfully on arm64. Cargo runs, but is killed (assumed to be resource pressure) when running in GitHub actions. It looks to be a problem for arm64 because no binarys are packaged for its architecture in the npm package.
The up and coming refactor in matrix-bot-sdk to use the rust-sdk directly might mean we can re-enable arm64 builds again, but at this moment in time it's simply too much of a time sink to work out why a binding layer we do not use (but, because the bot-sdk makes it a required dependency, we have to build it anyway) fails to compile.
=> Revert "Add docker auto-build for ARM64"

Dockerfile
This seems like a mistake we made when we split the install and build steps (due to the esbuild flakiness).
=> Dockerfile: Move --pure-lockfile to yarn (install) 

changelog.d/398.doc, docs/setup/gitlab.md, src/Webhooks.ts
GitLab test webhooks send a notification that isn't properly formed (missing an `action`). As a result, we can't handle them but users get frustrated that their notifications seemingly aren't working. They are, it's just that GitLab don't actually respect their own schema.
Instead, let's log a warning which can at least inform the admins that things are working but we can't handle the notification.
=> Add a warning when no action is given for GitLab

changelog.d/397.removal, config.sample.yml, docs/setup/webhooks.md, src/Config/Config.ts, src/Config/Defaults.ts, src/Webhooks.ts, src/generic/Router.ts
Fixes #395 
After polling the room, it sounds like most people don't need GET. The ones that do can enable the secret config flag to allow it, but in the general case it seems safe to be off by default.
=> Disable GET for webhooks (unless configured)

changelog.d/384.bugfix, src/Connections/SetupConnection.ts
The link in the AdminRoom is badly represented.
This will fix last part of #378 and #357.
I made this PR separatly from fix #379 cause I do not know if you prefer letting the client create the link (this PR) or force `<code></code>` tag (see https://github.com/psolyca/matrix-hookshot/commit/e1db4b2b140acff35c76c1ce86233be9acbbd72a).
EDIT: I have tested this with 3 different web client and the link is correctly created.
Signed-off-by: Damien Gaignon <damien.gaignon@gmail.com>
=> Fix link in AdminRoom

changelog.d/406.bugfix, src/Connections/GitlabRepo.ts
This was a mistake where we didn't correctly scope the filter to the same room.
=> Allow the same GitLab repo to be bridged to multiple rooms

Cargo.lock, changelog.d/388.bugfix, package.json, src/AdminRoom.ts, src/Bridge.ts, src/Notifications/GitHubWatcher.ts, src/Notifications/NotificationWatcherTask.ts, src/Notifications/UserNotificationWatcher.ts, src/UserTokenStore.ts, src/Webhooks.ts, yarn.lock
Fixes #387 
This makes the token store an emitter which emits an event when a token for a user is updated, allowing us to then emit a message to the watchers.
=> Automatically reconfigure GitHub notifications when a token is updated.

changelog.d/412.bugfix, config.sample.yml, src/Bridge.ts, src/Config/Config.ts, src/Config/Defaults.ts, src/Connections/GenericHook.ts, src/Connections/SetupConnection.ts, src/Widgets/SetupWidget.ts
If these settings are meant to be unspecified, then their entire parent
sections (`widgets` & `generic`) should be unspecified.
Signed-off-by: Andrew Ferrazzutti <andrewf@element.io>
=> Disallow some empty config URL settings

changelog.d/410.feature, docs/setup/webhooks.md, package.json, src/ListenerService.ts, src/generic/Router.ts, src/provisioning/provisioner.ts, yarn.lock
Does what it says on the tin. We also now document what formats we support in the documentation.
=> Add XML parser for generic webhook payloads

changelog.d/416.bugfix, src/AdminRoom.ts
`join`ing an array of empty strings with a non-empty separator makes the resulting string truthy, thus the condition for printing "No Github bridges" was never met.
=> Don't say nothing to no GitHub connections

changelog.d/415.doc, docs/usage/auth.md
instead of `github hastoken`, which was renamed.
Signed-off-by: Andrew Ferrazzutti <andrewf@element.io>
=> Mention `github login` and `github status` in docs

changelog.d/418.misc, src/Connections/CommandConnection.ts, src/Connections/GithubRepo.ts, src/Connections/GitlabRepo.ts, src/Connections/IConnection.ts, src/Connections/JiraProject.ts, src/Connections/SetupConnection.ts
This should prevent forgetting to add state event handlers in new or
existing connection types.
=> Share code for tracking config via state events

Dockerfile, changelog.d/438.misc
Optimizes docker image rebuilds following a code change, by installing dependencies before copying code so those layers can be cached. This speeds up cycles of build image -> code change -> build image again.
In my local testing, it's about 60s faster:
<details>
<summary>
No layers cached
</summary>
```
[+] Building 186.4s (22/22) FINISHED
=> [internal] load build definition from Dockerfile                                                                                                   0.0s
=> => transferring dockerfile: 37B                                                                                                                    0.0s
=> [internal] load .dockerignore …
```
=> Reorder dockerfile to optimize rebuilds

changelog.d/429.bugfix, src/Webhooks.ts
This is just a simple check to ensure we don't handle multiple events sent by GitHub by looking at the GUID provided. This is already pretty rare, but we've seen this happen rarely in the wild.
GitLab/JIRA don't support this as they don't provide a guid :s
=> Skip already handled GitHub events

changelog.d/440.misc, src/figma/index.ts
After seeing vague errors in production, it felt wise to make our errors cleaner, and also check that the access token is valid.
=> Validate figma access token + cleaner errors

changelog.d/443.bugfix, src/Connections/GenericHook.ts, tests/connections/GenericHookTest.ts
Fixes #442 
Let's just render them as paragraphs rather than inline.
=> Fix markdown paragraphs not rendering properly

changelog.d/ 441.feature, web/App.tsx, web/components/RoomConfigView.tsx
Adds support for a `serviceScope` query parameter in the config widget URL, which makes it go directly to a particular service (and removes navigation back to the list of services).
For example with `serviceScope=feeds`:
If the value provided for `serviceScope` does not correspond to a supported service, behavior will be as if it wasn't provided.
Fixes #437
=> Add query parameter to scope room config widget to a particular service

Dockerfile, changelog.d/448.bugfix
As it turns out, we need to run the script to build the all important crypto modules that we don't use. The --no-script is intended to avoid us trying to build the project, but in practise I think this does more harm than good (we don't seem to build when the production flag is used)
=> Remove --no-script from yarn

changelog.d/463.feature, docs/setup.md, src/LogWrapper.ts, src/Webhooks.ts
This PR attempts to make the JSON logger output more useful by pulling out metadata from the logs and storing them as keys. However, there was a fair amount of restitching needed to do this.
=> Useful JSON logger formatting

changelog.d/461.bugfix, src/AdminRoom.ts, src/Github/AdminCommands.ts, src/Jira/AdminCommands.ts
We lock logging into the bridge behind a permission level, "login". When attempting to login, the commands will always check permissions at the point of token storage but they were not checking at the point of executing the command, which meant users got confusing messages like:
> Token stored!
> Nevermind, you never had permission to do this!
This addresses the problem by simply being explicit about the permission level in the command metadata.
=> Fix GitHub/Jira/GitLab login not checking for permissions early enough

changelog.d/467.bugfix, src/App/BridgeApp.ts, src/Bridge.ts, src/LogWrapper.ts
#463 broke logging so that everything now logs at debug, which is less than helpful.
This also fixes the case where we don't log out errors before logging is configured.
=> Logging fixes

changelog.d/469.bugfix, src/Bridge.ts, src/feeds/FeedReader.ts
This caused:
```
/bin/matrix-hookshot/Bridge.js:402
this.bindHandlerToQueue("feed.success", (data) => connManager.getConnectionsForFeedUrl(data.feed.url), c => c.handleFeedSuccess());
^
TypeError: Cannot read properties of undefined (reading 'feed')
at Bridge.<anonymous> (/bin/matrix-hookshot/Bridge.js:402:101)
at LocalMQ.<anonymous> (/bin/matrix-hookshot/Bridge.js:494:61)
at LocalMQ.emit (node:events:513:28)
at LocalMQ.push (/bin/matrix-hookshot/MessageQueue/LocalMQ.js:31:14)
at FeedReader.pollFeeds (/bin/matrix-hookshot/feeds/FeedReader.js:199:28)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
=> Fix feed.success crashing the process due to a typing issue

changelog.d/480.feature, src/Bridge.ts, src/Connections/GitlabRepo.ts, src/Gitlab/WebhookTypes.ts, web/components/roomConfig/GitlabRepoConfig.tsx
Because GitLab webhooks are still quite cryptic, we're having to go based on what the title of the MR contains.
=> Support notifying when a GitLab MR is ready for review

changelog.d/481.bugfix, src/figma/index.ts
Because we decided to stick `v2/` in front of our client calls, all the requests would fail with a 404.
=> Fix figma not working on startup

changelog.d/478.misc, src/App/BridgeApp.ts, src/App/GithubWebhookApp.ts, src/App/MatrixSenderApp.ts, src/Config/Config.ts, src/Connections/CommandConnection.ts, src/LogWrapper.ts, tests/LogWrapperTest.ts, tests/init.ts
Fixes #477 
In addition to fixing the issue with JSON causing the bridge to error, this also adds some torture tests for the logger. It was a bit more refactor-y than I'd like but I think this does a good job of ensuring we won't break loggers so easily in the future.
=> Add Logger tests

changelog.d/484.bugfix, src/Connections/GitlabRepo.ts
Before this change, writing a review and commenting on a MR it would produce two notifications when really most users would expect one. This PR ensures that both comments and approval status are sent as one merged message.
=> Merge GitLab MR approvals and comments into one message

changelog.d/503.feature, docs/SUMMARY.md, docs/setup/jira.md, docs/usage/room_configuration/jira_project.md, src/Connections/SetupConnection.ts
This adds bot-command equivalents of the list & remove features that are available in the provisioning API, and soon, the configuration widget (note that this PR is not required by / dependent on the widget PR).
Note that this stops lower-casing the "safe URL" because that URL gets used as a state event key, which is case-sensitive, and wasn't lower-cased by the provisioning API (and isn't by the config widget either) -- meaning a connection added via a bot command couldn't be removed by the provisioning API (or widget), and vice-versa!
I'm pointing this out since the name of "safe URL" suggests that the lower-casing was done for a good reason, but AFAICT it only makes things worse.  (The rest of the "safety" in pulling apart irrelevant parts of the URL works great, though.)
=> Add commands to remove/list Jira connections

changelog.d/507.bugfix, web/components/roomConfig/JiraProjectConfig.tsx
Without this change, viewing the Jira widget without being logged into Jira causes the widget to repeatedly make network requests.
Note that this intentionally lacks a changelog since it fixes an issue with a yet-to-be-released feature (the Jira widget).
=> Fix Jira widget request loop for logged-out users

changelog.d/508.feature, src/ConnectionManager.ts, src/Connections/GithubRepo.ts, src/Github/Router.ts, src/Github/Types.ts, web/components/roomConfig/GithubRepoConfig.tsx
- Group repos by org
- Paginate repo requests
- Remove redundant label next to chosen repo
- Remove redundant repo field below connected repo
- Include repos that user has doesn't have admin permissions for, to achieve parity with results from provisioning API
---
This allows the widget's search UI to match Dimension's:
For what the GH widget looked like before, [see here](https://github.com/matrix-org/matrix-hookshot/pull/420#issuecomment-1192876562).
=> Reorganize the GitHub config widget

changelog.d/517.feature, web/components/elements/InputField.tsx, web/components/roomConfig/GitlabRepoConfig.tsx
=> Add label to GitLab widget's comment body toggle

changelog.d/518.misc, web/BridgeAPI.ts
Nitpick change to avoid a trailing `?` in `/widgetapi/v1/targets/<type>` query URLs when not using any filters.
=> Don't send empty query string in widget API reqs

changelog.d/512.feature, src/Bridge.ts
i.e. the same as is done for Jira
---
=> Send bot notice on GitHub OAuth success

changelog.d/519.bugfix, src/Connections/GithubRepo.ts
The bridge supports it, but schema validation didn't think so
=> Let GitHub widget support "issue.labeled"

changelog.d/520.feature, src/Bridge.ts, src/Connections/GithubRepo.ts
So we can spot failures, looks a bit like:
=> Add support for GitHub workflow run completion events

changelog.d/543.bugfix, docs/usage/room_configuration/jira_project.md, src/Bridge.ts, src/ConnectionManager.ts, src/Connections/IConnection.ts, src/Connections/JiraProject.ts, src/Webhooks.ts, web/components/roomConfig/JiraProjectConfig.tsx
- Refactor Jira event handling to be more like GitHub & GitLab
- Fix silently-ignored Jira events due to expecting wrong type strings
- Update UI for Jira events
---
This is the portion of #534 unrelated to version events, split into its own PR for better visibility.
=> Fix & refactor Jira issue event handling

changelog.d/540.feature, src/ConnectionManager.ts, src/Connections/BaseConnection.ts, src/Connections/CommandConnection.ts, src/Connections/IConnection.ts, src/Connections/JiraProject.ts, src/Widgets/BridgeWidgetApi.ts, src/provisioning/provisioner.ts
Fixes #533
Mitigates #421
----
Attempting to add a connection with a command prefix that's already in use for the room will fail:
=> Allow multiple Jira connections; stop prefix clash

changelog.d/528.feature, docs/usage/room_configuration/github_repo.md, src/ConnectionManager.ts, src/Connections/GithubRepo.ts, src/Connections/GitlabRepo.ts, src/HookFilter.ts, tests/HookFilter.ts, web/components/elements/InputField.tsx, web/components/roomConfig/GithubRepoConfig.tsx
Fixes #527 
This is my attempt to change our model so we can support events being disabled by default. The problem with the current state model is that `ignoreHooks` doesn't allow you to be explicit about what events you would like enabled, therefore there is now a second field called `enabledHooks`.
In the future, I am minded to refactor and drop ignoreHooks (except for backwards compat) and just make our default hooks explicit in the state event itself upon creation.
However, for now we can juggle two events. To make this easier, I've added a helper class and some tests.
=> Disable GitHub workflow events by default

changelog.d/536.bugfix, src/Connections/GitlabRepo.ts, src/Gitlab/WebhookTypes.ts
GitLab uses `discussion_id` to chain together replies. We can't really tell what position we are *in* the thread, so we just have to assume that if we've not seen the discussion before that we are the first note, and subsequent notes are child notes.
This also changes the code so that we skip sending a notice into the room if the user has disabled comment-only notices.
=> Skip GitLab MR reply comments

changelog.d/557.feature, src/Connections/GitlabRepo.ts
NOTE: If a room already contains multiple GitLab connections with case-insensensitive identical paths, they will _not_ be removed.
=> Make GitLab path uniqueness case-insensitive

changelog.d/558.misc, src/Bridge.ts, src/ConnectionManager.ts, src/Connections/SetupConnection.ts
Without this change, adding a connection with a bot command creates the connection, but doesn't store it in memory (by pushing it into the connection manager's list of known connections).  Thus, what would actually store the connection in memory was the bot responding to its own room state event, which made it provision the connection again from scratch.
=> Don't provision command-created connections twice

changelog.d/561.bugfix, src/Bridge.ts
=> Prevent users without permissions from inviting the bot

changelog.d/567.feature, docs/usage/room_configuration/gitlab_project.md, src/ConnectionManager.ts, src/Connections/GitlabRepo.ts, src/Connections/IConnection.ts, src/Connections/SetupConnection.ts, src/Widgets/BridgeWidgetApi.ts, src/provisioning/api.ts, src/provisioning/provisioner.ts, web/BridgeAPI.ts, web/components/elements/ErrorPane.module.scss, web/components/elements/ErrorPane.tsx, web/components/elements/WarningPane.module.scss, web/components/elements/WarningPane.tsx, web/components/elements/index.ts, web/components/roomConfig/RoomConfig.tsx, web/icons/error-badge.svg, web/icons/warning-badge.svg, web/typings/images.d.ts
Warn instead of fail when connecting a GitLab project that Hookshot cannot provision a webhook for.
---
This also updates documentation to explain that "Maintainer" or higher permissions are required on a GitLab project for Hookshot to be able to add a webhook to it.
The warning appears for both `hookshot gitlab project <url>` and the widget:
=> Allow GitLab connections without hook permissions

changelog.d/576.misc, src/AdminRoom.ts, src/Notifications/GitHubWatcher.ts, src/Widgets/BridgeWidgetApi.ts, src/api/error.ts, web/components/elements/ErrorPane.tsx, web/components/elements/WarningPane.tsx
=> Misspelling: occured -> occurred

changelog.d/565.bugfix, src/Bridge.ts, src/ConnectionManager.ts
If an unauthorized change to connection-related room state is detected, deny the new connection settings & attempt to revert the state change.
Also catch an otherwise-uncaught error on authentication failure.
=> Harden against unauthorized changes to room state

changelog.d/483.misc, config.sample.yml, src/Config/Config.ts, src/Config/Defaults.ts
10s seems too low in practice for things like GitHub, and it does seem to be doing more harm than good.
=> Increase feed.pollTimeoutSeconds from 10s to 30s

changelog.d/578.bugfix, src/Bridge.ts
This prevents a process restart from causing bot-created admin rooms to be forgotten.
=> Save bot-created admin rooms in profile data

changelog.d/539.bugfix, src/Connections/GitlabRepo.ts, src/Gitlab/Client.ts
Fixes #538 
Use a better API for checking access levels, that accounts for parent group permissions rather than just project permissions.
=> Check GitLab Repo access level via a better API

changelog.d/583.misc, src/feeds/FeedReader.ts
Fixes #570 
This actually fixes the error case in #570 and more, since it also introduces support for local side caching. A few services support this, so we might as well do it.
=> Add support for cached responses (ETags/LastModified) for RSS feeds

changelog.d/588.feature, docs/usage/room_configuration/github_repo.md, src/Connections/GithubRepo.ts
This allows teams to only report workflow runs that match a given name. Note the name is the `name` field given inside the workflow file, NOT the filename.
=> Support filtering workflow run on workflow names

changelog.d/582.bugfix, docs/usage/room_configuration/github_repo.md, src/Bridge.ts, src/Connections/GithubRepo.ts, web/components/roomConfig/GithubRepoConfig.tsx
Fixes #581 
This fixes a bug where drafted GitHub releases are no longer emitted by default, but under a different event type.
=> Split out GitHub release events into created and drafted

changelog.d/587.bugfix, src/Connections/GenericHook.ts, src/Connections/GithubRepo.ts, src/Connections/GitlabRepo.ts, src/Connections/JiraProject.ts
Fixes #584 
This also fixes a few validation bugs in GitHubRepo.
=> Ensure unknown keys are retained when connection state is altered via widget

changelog.d/299.feature, changelog.d/299.removal, config.sample.yml, docs/SUMMARY.md, docs/advanced/encryption.md, docs/advanced/workers.md, docs/metrics.md, package.json, registration.sample.yml, src/App/BridgeApp.ts, src/App/MatrixSenderApp.ts, src/Bridge.ts, src/Config/Config.ts, src/Config/Defaults.ts, src/ConnectionManager.ts, src/Connections/GenericHook.ts, src/MatrixSender.ts, src/Metrics.ts, src/Stores/RedisStorageProvider.ts, src/appservice.ts, yarn.lock
This PR adds support for native e2ee within the bridge, and drops support for Pantalaimon based bridging.
N.B this doesn't work yet, seeing failures like:
```
ERROR 11:34:53:742 [Appservice] Decryption error on !ltmLLVxeBLdNUWQISs:beefy $8gHWPs07YA8Ao-Ormsn71WwhHdP37VonGS8gfsYwKsU Error: Decryption failed: decryption failed because the room key is missing
at OlmMachine.decryptRoomEvent (/home/will/git/matrix-hookshot/node_modules/@turt2live/matrix-sdk-crypto-nodejs/src/ts/OlmMachine.ts:305:37)
at CryptoClient.<anonymous> (/home/will/git/matrix-hookshot/node_modules/matrix-bot-sdk/lib/e2ee/CryptoClient.js:157:50)
at Generator.next (<anonymous>)
at /home/will/git/matrix-hookshot/node_modules/matrix-bot-sdk/lib/e2ee/CryptoClient.js:17:71
at new Promise (<anonymous>)
at __awaiter …
```
=> Add support for native e2ee

changelog.d/606.misc, src/Webhooks.ts
10mb aught to do it, without being to excessive. I didn't feel the need to make this configurable, as really this is better configured in a load balancer.
=> Increase maximum size of webhook payload.

changelog.d/610.misc, config.sample.yml, docs/advanced/encryption.md, package.json, src/Config/Config.ts, src/Config/Defaults.ts
As discussed in #594, the bridge currently isn't stable with encryption enabled. Rather than ripping all the code out, we're going to mark it as experimental while it's still being worked on.
=> Mark encryption as experimental

changelog.d/602.feature, web/components/ConnectionCard.tsx, web/components/GitHubState.tsx, web/components/elements/ErrorPane.tsx, web/components/elements/WarningPane.tsx, web/components/roomConfig/RoomConfig.tsx
* `alt=""` indicates that there's no additional information in the image. It can be used for avatars and icons where the label is next to the image.
=> A11y: Add alt tags to all images

changelog.d/614.bugfix, package.json, src/Bridge.ts, src/ConnectionManager.ts, src/PromiseUtil.ts
Fixes #608 
This isn't really the best possible fix, but I think actually going through and eliminating all the possible ways we can fail a HTTP request on startup to be a significant effort. To avoid spinning too much time away on that, this change:
- Stops us from trying to fetch all state at once on startup at once concurrently, upsetting the homeserver. Instead, load 2 at a time. In the future we can increase this.
- Avoids `getRoomState` failures (which are probably the biggest explosion point) by retrying them on failure.
=> Decrease connection creation concurrency when starting up

changelog.d/617.bugfix, src/Connections/GitlabRepo.ts
We're checking to see if there are multiple connections with the same `path` in the room, but they might be on different instances!
=> Check the GitLab instance name when looking for existing connections

changelog.d/620.feature, src/Connections/SetupConnection.ts
Now in admin webhook info:
- Name of the hook
- Link to room (used a matrix.to link, because that seems to be working)
- URL on own line for better copying
closes #619
=> Add webhook name and room to admin info

changelog.d/643.doc, docs/advanced/service_bots.md, registration.sample.yml
Signed-off-by: Kim Brose <2803622+HarHarLinks@users.noreply.github.com>
Context: https://matrix.to/#/!TlZdPIYrhwNvXlBiEk:half-shot.uk/$AdcR43mfQlQq2p97UOgmIZTfUlmBVNbI7CtTQZ6_-74?via=half-shot.uk&via=matrix.org&via=element.io
Sample config
- disables feeds
- enables feeds serviceBot
- does not register feeds serviceBot namespace
This change fixes the latter, thus providing an example for anybody using servicebots.
[The spec](https://spec.matrix.org/unstable/application-service-api/#registration) isn't totally clear that this is needed, but it appears to be this way with synapse. Should the spec be updated to state this requirement more clearly?
Related: https://github.com/matrix-org/matrix-hookshot/issues/641
=> Register namespace for sample serviceBot in registration.sample.yml

changelog.d/660.bugfix, src/Widgets/BridgeWidgetApi.ts
Note, this only affected the UX of the frontend. Proper checks for user PL are still made at edit/creation time.
=> Fix hookshot showing connections as editable when the user has no permission

changelog.d/661.bugfix, package.json, src/Bridge.ts, src/Config/Config.ts, src/Connections/SetupConnection.ts, src/Github/GithubInstance.ts, src/Managers/BotUsersManager.ts, src/UserTokenStore.ts, src/Webhooks.ts, src/Widgets/BridgeWidgetApi.ts, src/Widgets/BridgeWidgetInterface.ts, tests/connections/GenericHookTest.ts, vite.config.js, web/BridgeAPI.ts, web/components/elements/ConnectionSearch.tsx, web/components/elements/DropdownSearch.tsx, web/components/roomConfig/Auth.tsx, web/components/roomConfig/FeedsConfig.tsx, web/components/roomConfig/GithubRepoConfig.tsx, web/components/roomConfig/RoomConfig.tsx, web/index.tsx, web/oauth.html, web/oauth.scss, web/oauth.tsx, web/styling.scss, yarn.lock
This PR does way more than intended, but it's all good stuff:
- Adds a new Auth component / endpoints for logging in, polling the state of, and logging out of GitHub.
- Adds a new OAuth.html page for showing a slightly nice success page than a single paragraph.
- Adds a new link for adding installations, the missing ingredient to make this work.
- Updates vite to support multi-page apps.
=> Add support for OAuth login to GitHub via widget (including adding new installations)

changelog.d/659.bugfix, src/Bridge.ts
Synapse no longer lets you kick yourself from a room with a reason, so instead we'll do the spec compliant thing of sending a leave with a reason. 
https://github.com/turt2live/matrix-bot-sdk/pull/301 is the upstream change we could rely on if it turned up in time.
=> Fix service bots not rejecting invites on incoming DMs

.github/workflows/docker-hub-latest.yml, changelog.d/662.misc
We need to include `pull_request` so docker builds are executed for community PRs.
=> Run docker CI for pull requests too

changelog.d/657.bugfix, src/Connections/SetupConnection.ts
Explicitly check for `undefined` when testing `roomSetupWidget`.
From the docs: „This can be enabled by setting roomSetupWidget to an object. “
If you set this to an object in the config:
```
widgets:
publicUrl: http://localhost:9000/widgetapi/v1/static
branding:
widgetTitle: Hookshot Konfig
roomSetupWidget:
```
The value of the parsed `roomSetupWidget` will be null → check fails
=> Fix widget config detection

changelog.d/663.bugfix, src/Webhooks.ts, src/Widgets/BridgeWidgetApi.ts
Basically, polling for the status of the oauth request causes the state to be removed, which makes the button useless.
=> Don't remove the oauth state on polling the status of the auth request

changelog.d/666.misc, src/Webhooks.ts, web/components/elements/ConnectionSearch.tsx, web/oauth.tsx
I felt like we should show a state for when an installation is pending. Also, refactor the oauth page to use proper typing.
=> Refactor oauth response page and show a pending state for GitHub installations

.github/workflows/release.yml, changelog.d/667.misc, scripts/release.sh
This basically ports https://github.com/matrix-org/matrix-appservice-bridge/pull/452 although I've made it a bit more agnostic to any package, so it should reasonably work if we ported it back.
=> Add release script

changelog.d/678.bugfix, web/BridgeAPI.ts
Fixes https://github.com/matrix-org/matrix-hookshot/issues/677
This means we have to bake a new token each time, which in the worst case might mean we hit ratelimits. These tokens are not terribly "expensive" as they only persist in memory/redis.
=> Continue even if localstorage is inaccessible

changelog.d/676.misc, src/App/BridgeApp.ts, src/App/GithubWebhookApp.ts, src/App/MatrixSenderApp.ts, src/Bridge.ts, src/ListenerService.ts
This should help us out a bit with few small issues:
- The ready state of each listener is directly mapped to whether it has resources bound, and we apply resources after the application is ready.
- This allows applications to check whether independent listeners of hookshot are ready.
- Liveness checks no longer wait for connections to start up...which is currently the case.
- As a bonus, we no longer logspam each ready check.
=> Add a ready probe to each listener and start the listeners immediately

changelog.d/680.bugfix, src/ConnectionManager.ts
To prevent exceptions from leaking back to the onRoomEvent handler.
=> Wrap createConnectionForState/ensureGrant in a try/catch

changelog.d/691.bugfix, src/Bridge.ts, src/PromiseUtil.ts, src/Widgets/BridgeWidgetApi.ts, src/provisioning/api.ts, web/components/roomConfig/RoomConfig.tsx
Soft dependency on https://github.com/matrix-org/matrix-appservice-bridge/pull/465
This should fix the cases where users see an error due to the invite not quite succeeding. This works by:
- Always ensuring we're joined to a room before testing permissions
- Making up to 10 (spaced by a second) checks for connections before giving up.
- Ensuring we log errors as JSON so we actually can check why we're failing.
=> Ensure joined to room when checking widget API permissions.

changelog.d/685.misc, src/Connections/FeedConnection.ts, src/feeds/FeedReader.ts
Rather than polling all the RSS feeds at once, let's stagger them and poll all the feeds within a single cycle of the poll interval. That way we at least spread the resource costs and stop memory spiking so much
Having tried this in "staging", this made things better:
=> Staggered RSS feed polling

changelog.d/672.bugfix, src/Connections/GithubRepo.ts
We should only supply the exact state required.
=> Fix grants supplying the wrong state

changelog.d/693.misc, scripts/release.sh
Noticed while doing 3.1.0 that we had outputted "-" as the release message.
=> Fix release script

changelog.d/694.bugfix, src/feeds/FeedReader.ts
Because there is a big difference between `Math.min` and `Math.max`.
=> RSS Spam fix

changelog.d/696.feature, docs/usage/room_configuration/github_repo.md, src/Bridge.ts, src/Connections/GithubRepo.ts, web/components/roomConfig/GithubRepoConfig.tsx
I've even gone and revitalized the concept of storing extra keys in the event body, so you can inspect which commits etc.
=> Support GitHub push events in repo connections

changelog.d/702.feature, docs/setup/feeds.md, src/Connections/FeedConnection.ts, src/feeds/FeedReader.ts, tests/connections/FeedTest.spec.ts, web/components/roomConfig/FeedsConfig.tsx
Fixes #698 
Look a bit like:
It features a very simple templating language. I was tempted to reuse the Generic Webhook API but it felt overkill and inaccessible for people just wanting to make their feeds a bit more bespoke.
=> Add support for templating feed messages

changelog.d/718.bugfix, src/Connections/GithubRepo.ts, src/Github/GrantChecker.ts
Believe this fixes #711 
Instead of relying on our internal cache for GitHub apps, let's just check on provisionConnection to see if GitHub has access to a repo.
=> Fix case where GitHub repos aren't connectable if the GitHub App was manually approved

changelog.d/716.feature, src/Connections/FeedConnection.ts, src/FormatUtil.ts, src/Notifications/GitLabWatcher.ts, src/Widgets/GoNebMigrator.ts, tests/FeedReader.spec.ts, web/components/elements/Button.module.scss, web/components/roomConfig/FeedsConfig.tsx, web/components/roomConfig/GenericWebhookConfig.tsx, web/components/roomConfig/GithubRepoConfig.tsx, web/components/roomConfig/GitlabRepoConfig.tsx, web/components/roomConfig/JiraProjectConfig.tsx, web/components/roomConfig/RoomConfig.tsx
Fixes https://github.com/matrix-org/matrix-hookshot/issues/541
Fixes https://github.com/vector-im/element-integration-manager/issues/63
This disables the notices by default when a feed fails, and adds a checkbox to opt in.
This also fixes a problem with the room configs not visibly changing when state is saved, by disabling the save/delete buttons while a save is in progress.
=> Add option to enable/disable feed failure notices.

changelog.d/714.feature, docs/advanced/encryption.md, package.json, src/App/BridgeApp.ts, src/App/MatrixSenderApp.ts, src/App/ResetCryptoStore.ts, src/Config/Config.ts, src/Stores/RedisStorageProvider.ts, src/Stores/StorageProvider.ts, src/appservice.ts, yarn.lock
Fixes https://github.com/matrix-org/matrix-hookshot/issues/609
=> Allow usage of the SQLite-based crypto store

changelog.d/750.misc, src/Config/permissions.rs, src/feeds/parser.rs, src/format_util.rs
Hi,
I applied the non style related clippy suggestions. (apart from the `map_clone` one and `single_match` in some places)
Namely:
- https://rust-lang.github.io/rust-clippy/master/index.html#single_match
- https://rust-lang.github.io/rust-clippy/master/index.html#explicit_counter_loop
- https://rust-lang.github.io/rust-clippy/master/index.html#redundant_closure
- https://rust-lang.github.io/rust-clippy/master/index.html#redundant_clone (coming from `to_string`)
- https://rust-lang.github.io/rust-clippy/master/index.html#map_clone
I also removed some calls to `format!` which should be not needed and allocate a `String` while not needed. (Though I am not sure if napi will do this anyway for FFI)
Signed-off-by: Marcel Radzio <support@nordgedanken.dev>
=> Apply cargo clippy suggestions to reduce not needed allocations

changelog.d/746.bugfix, src/Connections/GithubRepo.ts
Fixes that blockquotes don't get rendered as such. Leading spaces in front of `>` are not valid in commonmark. So they get not properly converted, but instead they seem to get escaped.
This PR was made on the assumption that the lib used follows commonmark spec as closely as it claims, and this being the logical result for this. I didn't have a test env handy to actually validate this.
Signed-off-by: Marcel Radzio <support@nordgedanken.dev>
=> fix: Make sure that the blockquote markdown for github issue comments are valid commonmark

changelog.d/755.bugfix, src/Bridge.ts
If the bot has PL 0, the bot incorrectly used the default power level.
Signed-off-by: Christian Paul <inbox-for-job-offers-from-element@chrpaul.de>
=> Fix #598; setup issues when the bot has PL 0 and room default isn't 0

Cargo.lock, Cargo.toml, changelog.d/786.bugfix, docs/metrics.md, docs/setup/feeds.md, package.json, src/Bridge.ts, src/Connections/FeedConnection.ts, src/Metrics.ts, src/Stores/MemoryStorageProvider.ts, src/Stores/RedisStorageProvider.ts, src/Stores/StorageProvider.ts, src/feeds/FeedReader.ts, src/feeds/parser.rs, tests/FeedReader.spec.ts, yarn.lock
Fixes #789 
This PR does several important perf fixes to the feed reader system. In particular we're trying to fix memory / storage consumption. To achieve this, the PR does two things:
- We drop the account data used by feed reader entirely, instead using Redis. This avoids having to store things in Hookshot's memory, and doing expensive load/save operations. Deployments of Hookshot using an in-memory storage provider will always initial sync on startup. This is a regression, but in practice it only means you miss items that were published during downtime. Anyone wishing for better reliability should be using Redis.
- We now read the feeds from Rust, avoiding the memory cost of shifting potentially huge blocks of XML across the native module boundary.
=> Performance improvements to Feeds

changelog.d/784.bugfix, src/feeds/parser.rs
=> Try to find an HTML-type link first when parsing atom feeds

changelog.d/795.feature, src/Connections/GithubRepo.ts
To make it easier to skim GitHub status updates, I think we should include an icon at the beginning of most messages.
I moved the approved/changes requested icon to the beginning of the message to be consistent and avoid breaking the flow of the words.
e.g. `User [checkmark icon] approved the following PR` seems cluttered compared to `[checkmark icon] User approved the following PR`.
Also, the length of the username would shift the position of the icon
Before:
```
John 📥 created an issue
Joe 📥 created an issue
Samantha 📥 created an issue
```
After:
```
📥 John created an issue
📥 Joe created an issue
📥 Samantha created an issue
```
=> Add more icons to GitHub messages

Cargo.lock, changelog.d/814.bugfix, package.json, yarn.lock
Depends on #798 
Since sled is removed, this now depends on @AndrewFerr 's work.
https://github.com/vector-im/matrix-bot-sdk/releases/tag/v0.6.7-element.1 includes some useful refactors to the appservice handler logic, specifically it fixes a leak where we would hold onto requests in pendingTransactions forever.
=> Update bot-sdk to 0.6.7-element-1

changelog.d/816.bugfix, src/feeds/FeedReader.ts, src/feeds/parser.rs
Things like TLS fails and timeouts were coming through as parsing failures, which is unfortunate because it was incorrectly highlighting a bug with our parser.
We also ensure that a `lpush` is not attempted with a empty array.
=> Ensure all forms of request failure on a feed are not treated as a parsing failure by metrics

Cargo.lock, Cargo.toml, changelog.d/819.misc, scripts/release.sh
This will help prevent cutting releases where the Cargo package version wasn't updated to match what's in package.json.
=> Update release script

changelog.d/826.misc, config.sample.yml, src/config/Config.ts, src/config/Decorators.ts, src/config/Defaults.ts
The previous version of the config included all the items as enabled, which broke bits of helm. Users should choose which features to enable instead.
=> Ensure sample config only defaults to bare minimum requirements

changelog.d/830.doc, docs/usage/auth.md
In hindsight it's very obvious that it need `repo` to get issue comments and other details for notifications from private repos, but it took me way to much time to think of that.
And, `repo:status` is above `public_repo` on the list of token permissions.
=> Add note about scope for private vs. public repo notifications

CHANGELOG.md, changelog.d/839.feature, docs/setup/webhooks.md, src/Bridge.ts, src/Connections/GenericHook.ts, src/config/Config.ts, src/generic/Router.ts, src/generic/types.ts, web/components/roomConfig/GenericWebhookConfig.tsx
Fixes #837 
This adds two new features to the generic webhook connection type:
- The ability to set a response value for webhooks.
- The ability for connections to choose whether to block on the webhook function before responding.
=> Add ability to respond to webhooks.

changelog.d/846.misc, scripts/release.sh
to ensure that the package versions to be committed are correct.
=> Update releaser script to check staged contents

Cargo.lock, Dockerfile, changelog.d/849.misc, package.json, src/Connections/GithubRepo.ts, src/figma/index.ts, yarn.lock
We can probably update to latest LTS now for Docker without issue. Also, we should try the slim variant again to see if it reduces total image size.
=> Use node:20-slim for Docker

changelog.d/865.bugfix, src/Connections/FeedConnection.ts, web/components/roomConfig/FeedsConfig.tsx
=> Fix feeds config UI not allowing notifyOnFailure to be toggled.

changelog.d/872.bugfix, spec/util/e2e-test.ts, spec/widgets.spec.ts, src/App/BridgeApp.ts, src/Bridge.ts, src/config/Config.ts, web/BridgeAPI.ts
This one escaped testing as my config locally has everything on a different port. Oh well. There is now an E2E test to ensure this doesn't re-break.
=> Fix widgets not working when bound to the same listener as webhooks.

changelog.d/873.bugfix, web/index.html
A small fuckup from before, the theme was being pinned to compound light causing things to look weird in dark mode.
=> Do not pin widget to light theme

changelog.d/875.bugfix, spec/github.spec.ts, spec/util/bridge-api.ts, spec/util/e2e-test.ts, spec/widgets.spec.ts, src/App/BridgeApp.ts, src/Webhooks.ts, src/github/GithubInstance.ts
At some point the API on the @octokit/webhooks library changed and it started requiring a full raw payload of the JSON data rather than a parsed body. To get around this, we store the raw string value of the body on the request object after verifying that the fields are valid. 
Ideally we'd validate in the verification function, but alas the GitHub function is async and the verifier expects a synchronous throw.
=> Fix GitHub events not verifying

changelog.d/874.bugfix, spec/util/e2e-test.ts, src/App/BridgeApp.ts, src/App/GithubWebhookApp.ts, src/App/MatrixSenderApp.ts, src/ListenerService.ts, src/api/error.ts
So we go from:
```
Error: API error HS_METHOD_NOT_ALLOWED: Invalid Method. Expecting PUT or POST
at GenericWebhooksRouter.onWebhook (/usr/bin/matrix-hookshot/generic/Router.js:41:19)
at Layer.handle [as handle_request] (/usr/bin/matrix-hookshot/node_modules/express/lib/router/layer.js:95:5)
at next (/usr/bin/matrix-hookshot/node_modules/express/lib/router/route.js:144:13)
at textParser (/usr/bin/matrix-hookshot/node_modules/body-parser/lib/types/text.js:69:7)
at Layer.handle [as handle_request] (/usr/bin/matrix-hookshot/node_modules/express/lib/router/layer.js:95:5)
at next (/usr/bin/matrix-hookshot/node_modules/express/lib/router/route.js:144:13)
at jsonParser (/usr/bin/matrix-hookshot/node_modules/body-parser/lib/types/json.js:110:7)
at Layer.handle [as handle_request] …
```
=> Fix logged errors not being properly formatted (and tone down the error verbosity a bit)

changelog.d/876.feature, docs/setup/feeds.md, src/Connections/SetupConnection.ts
The only other way currently to export all feeds from a room without loosing info is manually parsing the room state.
=> Add command to list feeds in JSON and YAML format

Cargo.lock, Cargo.toml, changelog.d/890.misc, spec/github.spec.ts, src/Connections/FeedConnection.ts, src/Stores/MemoryStorageProvider.ts, src/Stores/RedisStorageProvider.ts, src/Stores/StorageProvider.ts, src/feeds/FeedReader.ts, src/feeds/parser.rs, src/lib.rs, src/util/mod.rs, tests/connections/GithubRepoTest.ts
This should generally help speed up working feeds, by backing off failing ones. This is useful for environments with 1000s of feeds, some of which may have rotted since they were set up. For instance, integrations.ems.host sees about a 5% failure rate at the HTTP level alone.
Leftovers from this PR:
- Cache backoff times across restarts in Redis. We currently hit all feeds on startup and backoff again. We would need to provide a flush button though.
- General CPU improvements, now that we're failing less, the CPU is working harder.
=> Backoff failing RSS feeds

changelog.d/899.doc, config.sample.yml, docs/setup/github.md, src/config/Defaults.ts
The docs suggested that the Openid Connect callback url's should be at `/bridge_oauth`, but it should actually point to `/oauth
Resolves https://matrix.to/#/!TlZdPIYrhwNvXlBiEk:half-shot.uk/$surQW-4XHEJ8wgzzOClOF0QoWM-jjA1V5X3BlNQfQaw?via=half-shot.uk&via=matrix.org&via=element.io`
=> Change example Openid Connect callback url's to be correct.

Dockerfile, changelog.d/904.misc, docs/setup.md, src/ListenerService.ts
Set `NODE_ENV` to production to [increase performance](https://expressjs.com/en/advanced/best-practice-performance.html#set-node_env-to-production) and document it.
This also disabled the `X-Powered-By` header to avoid false positives by bad quality security scanners.
=> Use production mode

changelog.d/927.bugfix, docs/setup/challengehound.md, src/Connections/HoundConnection.ts, src/Stores/MemoryStorageProvider.ts, src/Stores/RedisStorageProvider.ts, src/Stores/StorageProvider.ts, src/hound/reader.ts, src/tokens/mod.rs
This refactors our cache layer to hash activities and check for changes.
=> Add support for edit tracking in challenge hound & fix a few bugs.

changelog.d/926.bugfix, package.json, src/generic/Router.ts, yarn.lock
A generic hook could potentially return a valid HTML document provided both `enableHttpGet` and JS functions are enabled. This isn't bad in itself but being able to execute JS is not really a useful feature.
=> Apply CSPs to generic hook responses.

changelog.d/929.bugfix, src/tokens/mod.rs, tests/tokens/tokenencryption.spec.ts
Fixes https://github.com/matrix-org/matrix-hookshot/issues/928
=> Fix PKCS1 handling

changelog.d/935.feature, docs/usage/room_configuration/gitlab_project.md, src/Bridge.ts, src/Connections/GitlabRepo.ts, tests/connections/GitlabRepoTest.ts, web/components/roomConfig/GitlabRepoConfig.tsx
=> Add support for reopened GitLab MR

changelog.d/936.bugfix, src/Connections/GitlabRepo.ts, src/Gitlab/WebhookTypes.ts
The code resulted on this error when there was a title change (rest of the stack trace omitted):
```
[Bridge] Connection GitLabRepo http://gitlab.local/group/website failed to handle gitlab.merge_request.update: TypeError: Cannot read properties of undefined (reading 'startsWith')
at GitLabRepoConnection.onMergeRequestUpdate (~/Projets/matrix/hookshot/src/Connections/GitlabRepo.ts:630:53)
```
As far back as I could go in the docs (GitLab 14.10), the keys for changes have been `previous` and `current`. Besides, there is a `draft` change that we can use directly instead of guessing from the title.
I removed the `[key: string]` type declaration because the type of the value depends on the key of the change.
=> Fix GitLab's ready for review hook

changelog.d/938.bugfix, src/Connections/GitlabRepo.ts
Contrary to GitHub, GitLab only uses `#` for issues. Merge requests use `!` as a prefix. This way, the bot messages are consistent with GitLab's interface.
=> Fix the symbol used to prefix GitLab merge requests

changelog.d/982.bugfix, src/Stores/MemoryStorageProvider.ts, src/Stores/RedisStorageProvider.ts, src/Stores/StorageProvider.ts, src/config/permissions.rs, src/format_util.rs, src/hound/reader.ts
Fixes #981 
If we haven't got anything in storage for challengehound, then it defaults to emitting everything to the room. This is a problem for memory-storage bots or unreliable Redis stores. To fix this, simply do not emit anything on first poll.
This also fixes a problem where we were endlessly adding the same hashes to Redis, using up more storage than required.
=> Fix challengehound duplication bug.

.github/workflows/newsfile.yml, changelog.d/987.misc
We've been skipping this check for years, and tbh I don't see the need to report package updates in the changelog.
=> Skip newsfile CI check for dependabot.

.envrc, .github/workflows/devenv.yml, .gitignore, changelog.d/993.misc, devenv.lock, devenv.nix, devenv.yaml
I use nix from time to time, and this makes my life easier. A workflow had been added to ensure nothing gets cocked up.
=> Add devenv development files

changelog.d/995.misc, jest.config.ts, spec/setup-jest.ts
We're seeing flakes due to https://github.com/matrix-org/complement/issues/720, so for now just retry a test if it fails in CI. We still want to fail locally so the error isn't entirely lost.
At some point this should be looked into on the complement side though.
=> Retry E2E tests on failure if running in CI.

.github/workflows/docker.yml, changelog.d/1008.misc
If we can pull this off, it would unlock building arm versions of hookshot much faster, which means we can run them for PRs.
=> Support building docker images for arm64 natively.

changelog.d/1041.bugfix, spec/permissions.spec.ts, spec/util/e2e-test.ts, spec/util/homerunner.ts, spec/webhooks.spec.ts, src/Connections/SetupConnection.ts, src/config/Config.ts, src/config/sections/generichooks.ts
Fixes https://github.com/matrix-org/matrix-hookshot/issues/1039
=> Ensure hookshot attempts to join configured permission room

.github/workflows/docs-latest.yml, .github/workflows/docs-release.yml, changelog.d/1043.misc
This can just be latest, since all it does is go and build the docs.
=> Update docs CI to use newer ubuntu

changelog.d/1051.feature, docs/setup/webhooks.md, src/App/BridgeApp.ts, src/Connections/GenericHook.ts, src/generic/transformer.ts, src/generic/types.ts, tests/connections/GenericHookTest.ts
This is so that users trying to setup alert bots and similar can do so without having to explicitly mention user ids / displaynames in the text.
=> Add intentional mentions to generic webhooks

changelog.d/1062.feature, package.json, spec/permissions.spec.ts, spec/util/e2e-test.ts, spec/util/homerunner.ts, src/Bridge.ts, yarn.lock
Simple tweak to help users who might otherwise be stuck with messages going missing. When paired with https://github.com/element-hq/synapse/pull/18521, this will also speed up recovery times.
=> Ping homeserver on startup and warn about configuration errors

changelog.d/1063.misc, docs/SUMMARY.md, docs/advanced/provisioning.md, docs/setup.md, docs/setup/github.md, docs/setup/gitlab.md, docs/setup/jira.md, spec/github.spec.ts, spec/gitlab.spec.ts, spec/jira.spec.ts, src/Bridge.ts, src/Webhooks.ts, src/github/Router.ts, src/gitlab/Router.ts, src/jira/Router.ts, src/notifications/UserNotificationWatcher.ts, src/openproject/Router.ts
This completes a longstanding task to move our older services to dedicated paths. The old paths will still work but may be removed in a future version.
=> Migrate GitHub, GitLab, and JIRA webhook path from `/` to `/<service>/webhook`

changelog.d/1066.misc, package.json, yarn.lock
So that manually verifying the device is possible, if a bit cumbersome.
=> Log encrypted device identity

docker-compose.yml
So that you can override the defaults.
=> invert docker-compose config order
