matrix-org/matrix-hookshot

- src/Config/Config.ts
- src/Connections/GitlabIssue.ts
- src/Connections/JiraProject.ts
- src/FormatUtil.ts
- src/GithubBridge.ts
- src/Jira/Types.ts
- src/Jira/WebhookTypes.ts
- src/Webhooks.ts
This PR adds support for listening to JIRA webhooks and sending messages into Matrix rooms. There will hopefully time for sending messages back to Matrix, but this is something at least :)
> Initial work to support JIRA

- .eslintrc.js
- config.sample.yml
- src/AdminRoom.ts
- src/App/BridgeApp.ts
- src/Bridge.ts
- src/Config/Config.ts
- src/Config/Defaults.ts
- src/ConnectionManager.ts
- src/Connections/CommandConnection.ts
- src/Connections/GithubDiscussion.ts
- src/Connections/GithubDiscussionSpace.ts
- src/Connections/GithubIssue.ts
- src/Connections/GithubRepo.ts
- src/Connections/GitlabIssue.ts
- src/Connections/GitlabRepo.ts
- src/Connections/IConnection.ts
- src/Connections/JiraProject.ts
- src/Connections/SetupConnection.ts
- src/Github/GithubInstance.ts
- src/Jira/Client.ts
- src/Jira/Types.ts
- src/Notifications/GitLabWatcher.ts
- src/UserTokenStore.ts
- src/Webhooks.ts
This supports GitHub Repos, Jira Projects and webhooks.
> Add `!setup` command to create new connections in rooms via bot commands

- src/Github/Router.ts
This does a number of things:
* Change the error codes on some responses so integration managers can pick up on it and show "Auth your org" sort of UI.
* Only reveal organizations and repos that are accessible via the installations, saving the integration manager from exception-based control flow.
* Treat the user's own name as an organization for alignment with traditional GitHub APIs. Typically speaking, "turt2live" is no different from "t2bot" for the purposes of UI and various older GitHub APIs.
* Whitespace fixes automatically applied by my editor (sorry)
> Use installations as reference for GitHub provisioning API

- src/Connections/GithubRepo.ts
For consistency with other things such as issues
> Use quotes instead of brackets in GH PRs

- changelog.d/104.feature
- src/Bridge.ts
- src/Connections/GitlabRepo.ts
- src/Gitlab/WebhookTypes.ts
- src/Webhooks.ts
> Support GitLab wiki page events

- changelog.d/111.bugfix
- docs/_site/style.css
- package.json
- scripts/build-app.sh
- scripts/definitions-fixer.ts
> Switch to build script

- changelog.d/124.doc
- config.sample.yml
- docs/_site/style.css
- docs/setup.md
- docs/setup/webhooks.md
- package.json
- src/Config/Config.ts
- src/Config/Defaults.ts
- src/ListenerService.ts
> Docs and config improvements

- changelog.d/130.feature
- docs/setup/webhooks.md
- src/Connections/GenericHook.ts
- tests/connections/GenericHookTest.ts
> Support `html` key on generic webhooks

- changelog.d/132.doc
- docs/setup.md
- docs/setup/github.md
- docs/setup/jira.md
> Explain that OAuth requests go through the webhooks listener

- Cargo.lock
- changelog.d/141.misc
- src/AdminRoom.ts
- src/BotCommands.ts
- src/ConnectionManager.ts
- src/Connections/CommandConnection.ts
- src/Connections/GithubRepo.ts
- src/Connections/JiraProject.ts
- src/Connections/SetupConnection.ts
This should ensure that both the !hookshot commands and the provisioning API use the same checks when attempting to connect a room to a service.
> Refactor setup commands

- changelog.d/166.bugfix
- src/Connections/JiraProject.ts
- src/Connections/SetupConnection.ts
Let's just use toUpperCase in all places.
> JIRA project keys MUST be uppercase when accessing the API

- changelog.d/222.feature
- src/Bridge.ts
- src/Connections/FigmaFileConnection.ts
- src/Connections/IConnection.ts
- src/figma/types.ts
Fixes https://github.com/matrix-org/matrix-hookshot/issues/217
I've migrated to using https://github.com/matrix-org/matrix-spec-proposals/pull/3440 for threads rather than the reply system from before. As a side effect this should stop the undefined issue.
> Use MSC3440 for Figma threads

- changelog.d/223.feature
- docs/setup/webhooks.md
- src/Connections/GenericHook.ts
- tests/connections/GenericHookTest.ts
> Add support for a "v2" webhook transformation API

- changelog.d/224.feature
- src/Connections/GenericHook.ts
- src/Webhooks.ts
- tests/connections/GenericHookTest.ts
> Prettify JSON output of generic hooks

- changelog.d/226.bugfix
- src/AdminRoom.ts
Supersedes https://github.com/matrix-org/matrix-hookshot/pull/181
This was written in a time when I thought I could get this working, but it's never actually been hooked into anything useful. I'm going to remove it so people don't get confused.
> Drop `gitlab notifications toggle` command

- changelog.d/230.bugfix
- src/Bridge.ts
Fixes https://github.com/matrix-org/matrix-hookshot/issues/205
> Remove extra `github.issues.edited`

- changelog.d/236.feature
- src/Connections/FigmaFileConnection.ts
Also fix the bolding issue #233
> Use m.thread for threads in figma

- changelog.d/243.doc
- docs/setup.md
> Clarify homeserver configuration and requirements in documentation

- changelog.d/247.bugfix
- src/Bridge.ts
Fixes an issue where webhook responses would always time out
> Fix generic webhook HTTP responses always timing out

- changelog.d/262.feature
- src/Connections/GithubRepo.ts
Also fix #261 where we sorted the dates on the comments in reverse
> Add support for closing comment on closed PRs

- changelog.d/264.doc
- docs/setup.md
* the setup vs (to) set up
* it's (it is) a lovely day vs. the dog lost its (third-person possessive pronoun) favourite toy
> Update setup.md: Minor grammar corrections

- changelog.d/277.feature
- config.sample.yml
- docs/usage/room_configuration/github_repo.md
- src/Config/Defaults.ts
- src/Connections/GithubRepo.ts
- src/FormatUtil.ts
- src/MatrixEvent.ts
> Support hotlinking github issues and PRs

- changelog.d/278.feature
- src/Bridge.ts
- src/Connections/GitlabRepo.ts
- src/Gitlab/WebhookTypes.ts
- src/Webhooks.ts
This MR shows a notice in GitLabRepo rooms when a new release is made.
> Support GitLab release events

- changelog.d/296.bugfix
- src/BotCommands.ts
- src/Connections/CommandConnection.ts
- src/Connections/GithubRepo.ts
- src/Connections/SetupConnection.ts
Also fixes #294  at the same time
> Ensure SetupCommand help command only shows enabled commands

- changelog.d/306.feature
- src/Bridge.ts
- src/Connections/GitlabRepo.ts
- src/Gitlab/WebhookTypes.ts
- src/Webhooks.ts
Fixes #252, #191
Supersedes #305
> Support gitlab push events

- changelog.d/312.feature
- docs/metrics.md
- src/Bridge.ts
- src/ConnectionManager.ts
- src/Connections/GithubIssue.ts
- src/MatrixSender.ts
- src/Metrics.ts
This PR:
- Reinstates the matrix-bot-sdk metrics that were previously missing
- Adds new metrics to record whether an event was handled successfully by connection(s)
> Improve metrics coverage

- changelog.d/321.feature
- config.sample.yml
- docs/SUMMARY.md
- docs/setup/gitlab.md
- docs/usage/room_configuration/gitlab_project.md
- src/AdminRoom.ts
- src/Config/Config.ts
- src/Config/Defaults.ts
- src/Connections/GitlabRepo.ts
- src/Connections/SetupConnection.ts
- src/Gitlab/Client.ts
- src/Gitlab/Types.ts
Fixes https://github.com/matrix-org/matrix-hookshot/issues/256
As a bonus, this also configures hooks.
> Add setup command for GitLab

- web/App.tsx
> Fix ErrorPane importing

- changelog.d/355.doc
- docs/setup.md
> Use https over git for install instructions

- changelog.d/370.misc
- web/App.tsx
> Add requireClient capability to widgets

- .github/workflows/docs-latest.yml
- .github/workflows/docs-release.yml
- CONTRIBUTING.md
- README.md
- changelog.d/134.doc
- docs/SUMMARY.md
- docs/contributing.md
To make it easier for folks to get started :)
**EDIT**: We're now basing this on https://github.com/matrix-org/matrix-appservice-bridge/pull/404.
> Add contributing file

- changelog.d/366.bugfix
- changelog.d/367.feature
- docs/setup.md
- src/AdminRoom.ts
- src/Bridge.ts
- src/Config/Config.ts
- src/Connections/GithubDiscussion.ts
- src/Connections/GithubDiscussionSpace.ts
- src/Connections/GithubIssue.ts
- src/Connections/GithubRepo.ts
- src/Github/GithubInstance.ts
- tests/AdminRoomTest.ts
> Add Admin command from listing and disconnecting connections

- changelog.d/372.bugfix
- src/AdminRoom.ts
- src/AdminRoomCommandHandler.ts
- src/Github/AdminCommands.ts
- src/Jira/AdminCommands.ts
#367 accidentally removed these when the category name was changed.
> Reinstate login commands for GitHub

- changelog.d/377.bugfix
- src/Github/AdminCommands.ts
- src/Github/GithubInstance.ts
- src/Github/Router.ts
- src/Webhooks.ts
- tests/github/AdminCommands.ts
Fixes #375 
I ended up refactoring how we generate URLs, and adding some sanity tests.
> Fix oauth login urls for GitHub cloud having the wrong domain

- changelog.d/403.bugfix
- src/Widgets/SetupWidget.ts
Signed-off-by: Andrew Ferrazzutti <andrewf@element.io>
> Allow proper responses to widget-setup commands

- changelog.d/411.bugfix
- src/Widgets/SetupWidget.ts
Fixes #308
Signed-off-by: Andrew Ferrazzutti <andrewf@element.io>
> Use the admin widget in admin rooms

- .github/workflows/sign-off.yml
- .github/workflows/signoff.yml
- changelog.d/427.misc
This reuses our signoff check from matrix-appservice-bridge.
> Add signoff check

- changelog.d/445.bugfix
- src/BotCommands.ts
- src/Bridge.ts
- src/Connections/CommandConnection.ts
Fixes https://github.com/matrix-org/matrix-hookshot/issues/393
This also introduces better error logging.
> Fix GitLab setup command

- src/feeds/FeedReader.ts
Signed-off-by: Kim Brose <2803622+HarHarLinks@users.noreply.github.com>
> Fix warn log typo

- changelog.d/457.bugfix
- src/provisioning/api.ts
> Don't look for `body` in an ApiError

- changelog.d/473.bugfix
- src/Webhooks.ts
I think I meant to actually set this to debug before :/
> Move noisy log line to debug

- changelog.d/491.bugfix
- src/Widgets/SetupWidget.ts
> Send a notice when the setup widget cannot be created

- changelog.d/496.feature
- src/Connections/GitlabRepo.ts
> Add support for creating confidential issues in GitLab

- changelog.d/500.feature
- docs/usage/room_configuration/gitlab_project.md
- src/Connections/GitlabRepo.ts
- web/components/roomConfig/GitlabRepoConfig.tsx
> Support GitLab MR comment bodies (optionally)

- changelog.d/505.misc
- src/Connections/GithubRepo.ts
- src/Connections/GitlabRepo.ts
- src/Connections/JiraProject.ts
- src/Widgets/BridgeWidgetApi.ts
- web/BridgeAPI.ts
- web/components/roomConfig/GitlabRepoConfig.tsx
- web/components/roomConfig/RoomConfig.tsx
Some type-checking improvements that make parts of the code more expressive & easier to work with.
Note that this is based on the config widget PR because it is the source of one of the type annotations added by this PR.
> Make various typechecking improvements

- changelog.d/515.bugfix
- src/Connections/GenericHook.ts
- src/Connections/GithubRepo.ts
- src/Connections/GitlabRepo.ts
- src/Connections/IConnection.ts
- src/Connections/JiraProject.ts
- src/Widgets/BridgeWidgetApi.ts
- web/components/roomConfig/GithubRepoConfig.tsx
- web/components/roomConfig/GitlabRepoConfig.tsx
- web/components/roomConfig/JiraProjectConfig.tsx
- web/components/roomConfig/RoomConfig.tsx
This also fixes the comment body toggle for GitLab widgets.
> Fix command prefix field in widgets

- changelog.d/522.bugfix
- src/AdminRoom.ts
> Add a note to use `help`

- changelog.d/524.bugfix
- src/AdminRoom.ts
- web/components/elements/InputField.module.scss
- web/components/elements/InputField.tsx
- web/components/roomConfig/GithubRepoConfig.tsx
Should have been part of #520 
Also, fixes two issues:
- Shows a more appropriate error when the user lacks permissions to list installations.
- Fixes the damn padding issue:
> Add checkboxes for workflow run statues in UI

- changelog.d/523.bugfix
- src/Github/AdminCommands.ts
- src/Github/GithubInstance.ts
- src/Github/Types.ts
- src/UserTokenStore.ts
While trying to investigate why the bridge stores an empty token when trying to perform a token refresh, I fixed these issues. For whatever reason, I cannot repro this problem on my local setup.
Having tested this on element.io, it doess seem to fix the issue.
> Improvements to GitHub auth

- .github/workflows/docker-hub-latest.yml
- .github/workflows/docker-hub-release.yml
- Dockerfile
- changelog.d/535.misc
> Fix Docker builds hanging/OOMing

- changelog.d/537.bugfix
- src/Bridge.ts
> Don't crash the bridge on state update failure

- changelog.d/551.bugfix
- src/feeds/FeedReader.ts
Going off https://github.com/axios/axios/issues/1174
> Silence RSS timeouts

- changelog.d/563.bugfix
- src/Config/Config.ts
> Remove trailing slashes from GitLab instance URLs

- changelog.d/556.feature
- src/Connections/GitlabRepo.ts
- src/Connections/SetupConnection.ts
> Display true casing of GitLab paths

- changelog.d/560.bugfix
- src/Connections/GenericHook.ts
I suspect #559 is failing because the body falls just outside our safe range. The safe ranges were chosen arbitrarily, but we can probably increase them without a huge perf penalty.
> Increase SANITIZE_MAX_BREADTH/SANITIZE_MAX_DEPTH for GenericHook

- changelog.d/568.doc
- docs/setup/github.md
- docs/setup/gitlab.md
- docs/usage/auth.md
> Update some doc links & formatting

- changelog.d/601.bugfix
- web/components/roomConfig/GenericWebhookConfig.tsx
* Improve performance by not modifying the `extensions` object and handler function on every re-render.
> Improve webhook code editor performance

- Dockerfile
- changelog.d/615.misc
Small tweak to make our builds go slightly faster
> Cache yarn dependencies

- changelog.d/628.bugfix
- src/ConnectionManager.ts
One single char can make a big difference :wink: 
closes #596
> Fix state update validation

- changelog.d/627.bugfix
- src/Connections/GenericHook.ts
- src/Connections/GithubDiscussion.ts
- src/Connections/GithubIssue.ts
- src/Connections/GitlabIssue.ts
- src/IntentUtils.ts
- tests/IntentUtilsTest.ts
- tests/connections/GenericHookTest.ts
- tests/utils/AppserviceMock.ts
- tests/utils/IntentMock.ts
> Fix generic webhook 'user is already in the room error'

- changelog.d/640.misc
- package.json
- src/Connections/GenericHook.ts
- src/Connections/SetupConnection.ts
- src/MatrixSender.ts
- src/MessageQueue/LocalMQ.ts
- src/MessageQueue/RedisQueue.ts
- src/UserTokenStore.ts
- src/feeds/FeedReader.ts
> Use replace uuid package with crypto.randomUUID

- changelog.d/652.misc
- web/App.tsx
- web/BridgeAPI.ts
- web/components/AdminSettings.tsx
- web/components/RoomConfigView.tsx
- web/components/elements/Card.module.scss
- web/components/elements/Card.tsx
- web/components/elements/LoadingSpinner.module.scss
- web/components/elements/LoadingSpinner.tsx
- web/components/elements/index.ts
- web/components/roomConfig/FeedsConfig.tsx
- web/components/roomConfig/GenericWebhookConfig.tsx
- web/components/roomConfig/GithubRepoConfig.tsx
- web/components/roomConfig/GitlabRepoConfig.tsx
- web/components/roomConfig/JiraProjectConfig.tsx
- web/components/roomConfig/RoomConfig.tsx
- web/styling.scss
Adds some small but impactful style changes to the widget UI:
* Light gray background
* Card styles around config forms
* Animated loading spinner
Also adds support for the `io_element_embed_type` parameter so that when embedded in an integration manager, padding is removed and headers are hidden.
> Improve widget style

- changelog.d/664.misc
- web/components/elements/ConnectionSearch.tsx
Fixes the grammar in this link, as well as puts it on the next line.
> Fix add instance link grammar

- changelog.d/665.bugfix
- src/Connections/GithubRepo.ts
> Fix GitHub grant checker not checking the correct ID

- changelog.d/670.bugfix
- src/feeds/FeedReader.ts
These did more harm then good, breaking many legit feeds in weird ways.
> Undo XML parser customizations

- .github/workflows/docker-hub-latest.yml
- .github/workflows/docs-latest.yml
- .github/workflows/main.yml
- .github/workflows/newsfile.yml
- changelog.d/692.misc
Just to save a few pennies on CI.
> Ignore paths in workflows if only updating the changelog

- changelog.d/700.feature
- src/feeds/FeedReader.ts
Fixes https://github.com/vector-im/element-integration-manager/issues/67
> Add support for using guid as a feed link

- changelog.d/697.feature
- src/Bridge.ts
- src/Connections/GithubRepo.ts
- web/components/roomConfig/GithubRepoConfig.tsx
Another Go-NEB parity feature with https://github.com/vector-im/element-integration-manager/issues/60
> Add support for showing GitHub issue comments

- src/App/ResetCryptoStore.ts
Ensure that the bridge storage is always disconnected
---
Without this, `yarn start:resetcrypto` hangs if E2EE is disabled in the config file.
> Fix hang in crypto reset script when E2EE is off

- changelog.d/737.bugfix
- src/Connections/FeedConnection.ts
- tests/connections/FeedTest.spec.ts
Fixes https://github.com/matrix-org/matrix-hookshot/issues/731, https://github.com/vector-im/element-integration-manager/issues/92
> Fix message format for feed items with no title or link

- docs/_site/main.js
#719 adds helm releases, which we don't need in the docs :)
> Skip helm releases in docs

- changelog.d/800.misc
- package.json
- yarn.lock
> Update matrix-appservice-bridge to 9.0.1

- changelog.d/818.bugfix
- src/Connections/GenericHook.ts
- tests/connections/GenericHookTest.ts
> Fix top level return incompatibility

- changelog.d/821.misc
- helm/hookshot/values.yaml
Fix for https://github.com/matrix-org/matrix-hookshot/issues/821 and https://github.com/vector-im/sre-internal/issues/2840
> Hookshot optionals

- changelog.d/826.misc
- helm/hookshot/Chart.yaml
- helm/hookshot/values.yaml
- Release helm chart `0.1.15`
- Add note to helm `values.yaml` file
> Release chart 0.1.15

- changelog.d/843.bugfix
- docs/_site/main.js
> Fix missing version picker on docs.

- changelog.d/852.feature
- src/Widgets/BridgeWidgetApi.ts
- src/provisioning/api.ts
- web/components/roomConfig/RoomConfig.tsx
> Warn if the bot cannot send a message in the widget

- changelog.d/866.feature
- src/Connections/SetupConnection.ts
Basic copy of what we did for feeds but for webhooks.
> Add commands for listing & removing webhooks

- changelog.d/870.bugfix
- web/App.tsx
Introduced back in https://github.com/matrix-org/matrix-hookshot/pull/862/files#diff-ae06e7ad915744def412154ac608215bf6abd9a8873d3e1773d1531e5e22a5fb
> Fix widgets failing to connect.

- changelog.d/869.misc
- src/Connections/GithubRepo.ts
https://github.com/calamares/calamares/issues/2263
> sucessfully

- changelog.d/889.feature
- src/Connections/GithubRepo.ts
- tests/connections/GithubRepoTest.ts
> Add support for mentioning multiple assignees on GitHub issues

- changelog.d/891.feature
- src/Connections/FeedConnection.ts
Hopefully helps with the failure mode we're seeing in #844
> Retry failed RSS entries 

- Cargo.lock
- Cargo.toml
- changelog.d/930.bugfix
- src/tokens/UserTokenStore.ts
- src/tokens/mod.rs
- tests/tokens/tokenencryption.spec.ts
I neglected to check which padding algorithm was in use.
> Fix tokens encrypted with Node crypto implementation being undecryptable in new Rust implementation.

- README.md
> Add challengeHound to README

- changelog.d/937.bugfix
- src/Connections/GitlabRepo.ts
> Fix rendering of comments of GitLab merge requests

- .github/workflows/devenv.yml
- changelog.d/996.misc
- package.json
- yarn.lock
This should bring us up to reasonably the latest version of the rust sdk, which should generally improve reliability etc.
> Update matrix-bot-sdk 0.7.1 element.7

- changelog.d/1019.bugfix
- package.json
- src/Connections/GenericHook.ts
- src/IntentUtils.ts
- src/Managers/BotUsersManager.ts
- tests/utils/IntentMock.ts
- yarn.lock
Requires https://github.com/element-hq/matrix-bot-sdk/pull/54
> Fix webhooks not being handled when profile changes are forbidden

- changelog.d/1756.bugfix
- src/Bridge.ts
- src/CommentProcessor.ts
- src/Connections/GitlabRepo.ts
- src/Gitlab/WebhookTypes.ts
- src/config/sections/encryption.ts
- src/feeds/FeedReader.ts
- tests/connections/GitlabRepoTest.ts
Might fix #1017 (waiting for feedback)
Small oversight on the filtering logic.
> Filter GitLab comments with include/exclude label config.

- .github/workflows/docker.yml
- changelog.d/1046.misc
> Don't login to docker for dependabot PRs

- .github/workflows/docker.yml
> Stop docker builds happening twice on PRs

- changelog.d/1033.bugfix
- src/Connections/GithubRepo.ts
Fixes #1032 
Signed-off-by: Vladimir Pal <this@vlad-pal.net>
> Fix case-sensitive GitHub username comparison

- changelog.d/1058.bugfix
- docs/metrics.md
- scripts/build-metrics-docs.ts
> Fix metrics docs not rendering correctly

- docker-compose.yml
> invert docker-compose config order
